### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by mageshravi** [KeerthanaS15/docline247#3]
Implement the home page as described in [figma file](https://www.figma.com/file/zfh3OFhRfAFtLsfs55wcGZ/?node-id=0%3A1).

Backend:

- Setup a class-based view, template and url config.
- Configure `static` folder.

Frontend:

- Setup node/npm/yarn to compile `scss` into `css`.
- Implement the HTML/CSS based on the Figma design.

Steps:

- Jeevitha to create a new branch. Make the backend changes, commit and push them.
- Keerthana to pull the branch with changes from Jeevitha, then add frontend changes on top.

**Comment by Jeevitha-10** [comment]
Home page completed
